# Default values for croc-hunter.
# This is a YAML-formatted file.
# Declare name/value pairs to be passed into your templates.
# name: value

serviceType: ClusterIP
servicePort: 80
containerPort: 8080
component: "jblue-test"
replicas: 2
image: "10.233.61.72:5000/test/jblue-test"
imageTag: "latest"
imagePullPolicy: "Always"
## If you have a private registry you specify a secret to use
#imagePullSecrets:
cpu: "10m"
memory: "128Mi"
## Ingress settings
ingress:
  enabled: true
  hostname: test.eqap.io
  annotations:
     kubernetes.io/ingress.class: traefik
     kubernetes.io/tls-acme: "true"
  tls: true
## PodDisruptionBudget
pdb:
  enabled: false
  minAvailable: 2
